import { InjectorToken } from '@hwy-fm/di';
export declare const SYNC = "Sync";
export declare const TABLE = "Table";
export declare const ENTITY = "Entity";
export declare const COLUMN = "Column";
export declare const ASSOCIATION = "Association";
export declare const DATABASE = "database";
export declare const HAS_ONE = "hasOne";
export declare const HAS_MANY = "hasMany";
export declare const BELONGS_TO = "belongsTo";
export declare const BELONGS_TO_MANY = "belongsToMany";
export declare const TRANSACTION = "Transaction";
export declare const ENTITY_QUEUE: InjectorToken;
