import { Type } from '@hwy-fm/di';
import { RequestHandler } from 'express';
import { hookFunc } from './context';
import { ControllerOptions, MethodHookFunc } from './router-manager';
type ModelOptions = {
    controller: Type[];
};
export declare const Controller: (baseUrl?: string, options?: ControllerOptions) => ClassDecorator;
export declare const ControllerModel: (options: ModelOptions) => ClassDecorator;
export declare const Get: (url: string | string[], ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const All: (url: string | string[], ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const Use: (url?: string | string[] | RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>, ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const Put: (url: string | string[], ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const Post: (url: string | string[], ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const Param: (url: string | string[], ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const Delete: (url: string | string[], ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const Options: (url: string | string[], ...middleware: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const Middleware: (...args: RequestHandler<import("express-serve-static-core").ParamsDictionary, any, any, import("qs").ParsedQs, Record<string, any>>[]) => MethodDecorator;
export declare const makeRouteMethodDecorator: <T>(hook: MethodHookFunc) => (options?: T) => MethodDecorator;
export declare const Ip: () => import("@hwy-fm/di").TargetDecorator;
export declare const Req: () => import("@hwy-fm/di").TargetDecorator;
export declare const Res: () => import("@hwy-fm/di").TargetDecorator;
export declare const Next: () => import("@hwy-fm/di").TargetDecorator;
export declare const Body: (key?: string) => import("@hwy-fm/di").TargetDecorator;
export declare const Query: (key?: string) => import("@hwy-fm/di").TargetDecorator;
export declare const Params: (key?: string) => import("@hwy-fm/di").TargetDecorator;
export declare const Headers: (key?: string) => import("@hwy-fm/di").TargetDecorator;
export declare const makeRouteParamsDecorator: <T>(transform: hookFunc) => (options?: T) => import("@hwy-fm/di").TargetDecorator;
export {};
